[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[main]]
name = "Presentations"
weight = 300
identifier = "presentations"
url = "/presentations/"

[[main]]
name = "About"
weight = 400
identifier = "about"
url = "/about/"

[[footer]]
name = "imprint"
weight = 1
identifier = "imprint"
url = "/imprint/"