title = "Data World Living"
author = "Arne Rossmann"
description = "I'm Arne Rossmann, a CTO in the Data & AI field & innovation enthusiast"
profilePicture = "images/profile.jpg"
displayMode = "dark"
contentratio = 0.85
mainSections = ["post"]
doNotLoadAnimations = true

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/arnerossmann/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/arnerossmann"

[[socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://techhub.social/@arnerossmann"
